### PR TITLE
feat: add testnet feedback form

### PR DESCRIPTION
**Pull request by akintewe**
## Description
Added a feedback form component for testnet phase user feedback collection.

### Changes
- Created new `FeedbackForm` component
- Added form validation with required fields
- Integrated with existing design system
- Added disabled state for submit button until form is valid
- Placed form below main app content

### Features
- Rate experience (1-10)
- Reading satisfaction rating (1-10)
- Willing to pay amount (in APT)
- Mainnet usage intention
- Open feedback field

### Design
- Matches existing app styling
- Full-width card layout
- Consistent with other components
- Responsive design

### Testing
- [ ] Form validation works as expected
- [ ] Submit button state changes correctly
- [ ] Toast notification shows on submit
- [ ] Form resets after submission
- [ ] Responsive on different screen sizes

### Screenshots
Screenshot 2024-12-13 at 10 02 10 AM

### CODE REVIEW

**Comment by huisq** [comment]
where is the collected information stored, and how is this presented visually? The form aesthetic is not presentable with current design

**Comment by akintewe** [comment]
> where is the collected information stored, and how is this presented visually? The form aesthetic is not presentable with current design

i've updated the feedback form to store all submissions in localStorage with timestamps and IDs, making it easy to track and review feedback. The design has been simplified to match the site's aesthetic while remaining minimal and functional. Users can now view their previous submissions in a collapsible section below the form, and the layout has been improved for better readability and user experience.    
Screenshot 2024-12-19 at 8 39 59 PM

**Comment by huisq** [comment]
There's no backend storage for this and your design completely did not consider storage issue at all. I'll have to reject this issue.

**Comment by akintewe** [comment]
> There's no backend storage for this and your design completely did not consider storage issue at all. I'll have to reject this issue.

Can i get further explanation of this, because i worked based on the issue description

**Comment by huisq** [comment]
how would you expect information to store in localhost while enabling site owner to get the feedback answers? the issue description was to use a service such as google form or typeform so to not have to store any data in backend. while only adding a small entry point like a icon on the website that does not obstruct current features and design.

**Pull request closed without merging**
